### PR TITLE
Feature file search

### PR DESCRIPTION
**Pull request by SpartArs**
Search for a file by name in the tree.

It works like this:
- Enter the file name in the search field (case and spaces are ignored)
- Press Enter
- The found file is displayed in the tree
- The code area displays the contents of the file

I made the search field not hidden. In my opinion, it is convenient and faster to work this way.

### CODE REVIEW

**Comment by Col-E** [comment]
With your implementation if you rename a class, you'll still need to refer to it by the old name. Is that intentional?

Copying some of the logic from the tree-cell you can have renamed files be accessible by the search:

```java
treeTraversal(tree.getRoot(), treeItem -> {
	if (treeItem != null) {
		String fullPath = treeItem.fullPath;
		String currentName = fullPath;

		CMap map = Mappings.INSTANCE.getClassMapping(fullPath);
		if (map != null)
			currentName = map.getCurrentName();
		
		if (currentName != null) {
			String searchText = fileSearch.getText().replaceAll("\\s", "");
			if (trim(currentName).equalsIgnoreCase(searchText)) {
				// display found file in tree
				FileTreeItem foundNode = getNode(currentName);
				tree.getSelectionModel().select(foundNode);
				Threads.runFx(tree::requestFocus);
				// display content of this file in CodePane
				Bus.post(new ClassOpenEvent(fullPath));
			}
		}
	}
});
```

**Comment by SpartArs** [comment]
How to think in this case, in the `ClassOpenEvent` must also pass `currentName`?

`Bus.post(new ClassOpenEvent(currentName));`

**Comment by Col-E** [comment]
The reason why we don't use the `currentName` for the `ClassOpenEvent` is because technically nothing is actually changed until we export the modified file. All the renamed code you see in the UI is done on the fly. The backend is still all using the original name _(`fullPath`)_

If you try and use the current name for the event, it will fail to find the file and not open anything.

**Comment by Col-E** [comment]
:+1: I'll merge if you don't have any additional commits to add

**Comment by SpartArs** [comment]
Ok! I don't have any addition.

**Comment by Col-E** [comment]
Thanks for the PR :+1:  Merged

**Pull request merged**
