### PR TITLE
Add maven suppport

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by Col-E** [comment]
I feel kinda bad that I forgot this pull existed. Anyways I'm don't see this project as something complex enough to warrant converting it to a maven project.

**Comment by FFY00** [comment]
I didn't implement maven because the project was complex but to make it easier to compile and configure in Jenkins.

**Comment by Col-E** [comment]
Ah. I'm not familiar with Jenkins. Does github have integration for it or would you have to host a Jenkins server on your own?

**Comment by FFY00** [comment]
I have my own local Jenkins server but there are other free self-hosting alternatives like AppVeyor.

**Pull request closed without merging**
